
#ifndef __CONFIG_H__
#define __CONFIG_H__

//#define DEBUG_OLED_DISPLAY

#define FIRMWARE_MAJOR_VERSION 3
#define FIREWARM_MINOR_VERSION 0

#define FW_STRING_LEN 25

#define DEFAULT_HIGH_TEMP_THRESHOLD 3900
#define MIN_TEMP_THRESHOLD 3600
#define MAX_TEMP_THRESHOLD 4200

#define PRE_RELEASE

#endif

